name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - uses: r7kamura/rust-problem-matchers@v1
    - name: Run clippy
      run: cargo clippy --all-targets --no-deps -- -W clippy::all
